apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-push-latest
  namespace: sample-php-cicd
spec:
  pipelineRef:
    name: build-push
  params:
  - name: deployment-name
    value: sample-php
  - name: git-url
    value: https://github.com/giofontana/rhel-ubi-apache-sample.git
  - name: IMAGE
    value: quay-registry-quay-openshift-operators.apps.cluster-blkz2.blkz2.sandbox548.opentlc.com/demo/sample-php:latest
  - name: acs_central_endpoint
    value: acs-secret
  - name: acs_api_token
    value: acs-secret    
  workspaces:
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
