apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: set-image
  namespace: sample-php-cicd
spec:
  params:
    - name: k8s-deployment-path
      description: Path to the deployment yaml
      type: string
      default: k8s/deployment.yaml
    - name: image
      description: Image url
      type: string
  steps:
    - name: set-image
      image: registry.access.redhat.com/ubi8/ubi
      resources: {}
      command:
        - /bin/bash
        - -c
        - |
          set -e
          echo "Setting image on deployment YAML"

          #microdnf -y install git > /dev/null 2>&1
          dnf -y install git

          cd /files
          FILE=$(params.k8s-deployment-path)
          ESCAPED_IMAGE_PATH=$(printf '%s\n' "$(params.image)" | sed -e 's/[]\/$*.^[]/\\&/g');

          sed -i s/IMAGE/${ESCAPED_IMAGE_PATH}/g $FILE

          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          git config --global user.email "demo@redhat.com"
          git config --global user.name "Demo User"
          git add $FILE
          git commit -m 'Set image'
          git push -u origin $CURRENT_BRANCH
          
      workingDir: /workspace
  workspaces:
  - name: files
    mountPath: /files
