apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: configure-gitops-cluster
  namespace: sample-php-cicd
spec:
  workspaces:
  - name: source
  params:
    - name: argocd_config_dir
      description: The directory in source that contains yaml manifests
      type: string
      default: "./Argocd/configuration"
  steps:
    - name: apply
      image: registry.redhat.io/openshift4/ose-cli:latest
      workingDir: /workspace/source
      command: ["/bin/bash", "-c"]
      args:
        - |-
          echo Applying manifest $(inputs.params.argocd_config_dir) to configura ArgoCD GitOps Cluster
          oc apply -k $(inputs.params.argocd_config_dir)
          echo -----------------------------------
