apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-using-argocd
spec:
  workspaces:
  - name: source
  params:
    - name: argocd_app_manifest
      description: The manifest file that contains yaml manifests
      type: string
  steps:
    - name: apply
      image: registry.redhat.io/openshift4/ose-cli:latest
      workingDir: /workspace/source
      command: ["/bin/bash", "-c"]
      args:
        - |-
          echo Applying manifest $(inputs.params.argocd_app_manifest) to create ArgoCD Application
          oc apply -f $(inputs.params.argocd_app_manifest)
          echo -----------------------------------
