apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sample-php
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: sample-php-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: sample-php-{{name}}
      labels:
        velero.io/exclude-from-backup: "true"
    spec:
      project: default
      source:
        repoURL: https://github.com/giofontana/rhel-ubi-apache-sample.git
        targetRevision: workshop
        path: k8s
      destination:
        namespace: sample-php
        server: "{{server}}"
      syncPolicy:
        automated:
          selfHeal: false
          prune: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=orphan
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: sample-php-placement
  namespace: openshift-gitops
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: env
              operator: In
              values:
                - prod
