apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sample-php
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - cluster: prod
        url: https://api.prod.sandbox1759.opentlc.com:6443      
      - cluster: prod2
        url: https://api.prod2.sandbox1759.opentlc.com:6443
  template: 
    # This is a template Argo CD Application, but with support for parameter substitution.
    metadata:
      name: 'sample-php-{{cluster}}'
    spec:
      project: "default"
      source:
        repoURL: 'https://github.com/giofontana/rhel-ubi-apache-sample.git'
        targetRevision: main
        path: k8s
      destination:
        server: '{{url}}'
        namespace: sample-php
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=orphan

