apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-php
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/giofontana/rhel-ubi-apache-sample.git'
    path: k8s
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
