apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy
spec:
  workspaces:
  - name: shared-workspace
  params:
  - name: git-url
    type: string
    description: url of the git repo for the code of deployment
    default: "https://github.com/giofontana/rhel-ubi-apache-sample.git"
  - name: git-revision
    type: string
    description: revision to be used from repo of the code for deployment
    default: "main"
  - name: argocd_app_manifest
    type: string
    description: The directory in source that contains yaml manifests
    default: "./cd/Argocd/sample-php-app.yaml"
  tasks:
  - name: fetch-repository
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.git-url)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    - name: revision
      value: $(params.git-revision)
  - name: deploy-using-argocd
    params:
    - name: argocd_app_manifest
      value: $(params.argocd_app_manifest)
    taskRef:
      kind: Task
      name: deploy-using-argocd
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter:
    - fetch-repository
