apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-push
spec:
  workspaces:
  - name: shared-workspace
  params:
  - name: deployment-name
    type: string
    description: name of the deployment to be patched
    default: "sample-php"
  - name: git-url
    type: string
    description: url of the git repo for the code of deployment
    default: "https://github.com/giofontana/rhel-ubi-apache-sample.git"
  - name: git-revision
    type: string
    description: revision to be used from repo of the code for deployment
    default: "main"
  - name: IMAGE
    type: string
    description: image to be build from the code
  - name: CONTEXT
    type: string
    description: Path to the application source code directory   
    default: "."
  - name: acs_central_endpoint
    type: string
    default: "acs-secret"
  - name: acs_api_token
    type: string
    default: "acs-secret"
  - name: manifests-location-in-git-repo
    type: string  
    default: "./k8s"
  - name: recursive-search
    type: string   
    default: "true" 
  tasks:
  - name: fetch-repository
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.git-url)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    - name: revision
      value: $(params.git-revision)
  - name: security-check
    params:
    - name: acs_central_endpoint
      value: $(params.acs_central_endpoint)
    - name: acs_api_token
      value: $(params.acs_api_token)
    - name: source_location
      value: $(params.manifests-location-in-git-repo)
    - name: recursive-search
      value: $(params.recursive-search)
    taskRef:
      kind: Task
      name: acs-deployment-check
    workspaces:
    - name: files
      workspace: shared-workspace
    runAfter:
    - fetch-repository     
  - name: build-and-push-image
    taskRef:
      name: buildah
      kind: ClusterTask
    params:
    - name: IMAGE
      value: $(params.IMAGE)
    - name: CONTEXT
      value: $(params.CONTEXT)      
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter:
    - security-check
    
