apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- Tasks/deploy-using-argocd.yaml
- Tasks/configure-gitops-cluster.yaml
- Pipeline/deploy-local.yaml
- Pipeline/deploy-remote-clusters.yaml

namespace: sample-php-cicd
