apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: deploy-remote-clusters
  namespace: sample-php-cicd
spec:
  pipelineRef:
    name: deploy-remote-clusters
  params:
  - name: deployment-name
    value: sample-php
  - name: git-url
    value: https://github.com/giofontana/rhel-ubi-apache-sample.git
  - name: argocd_app_manifest
    value: "./cd/Argocd/sample-php-appset.yaml" 
  workspaces:
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
