apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- Tasks/acs-deployment-check.yaml
- Tasks/set-image.yaml
- Pipeline/build-push.yaml

namespace: sample-php-cicd
